import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers":
    "Content-Type, Authorization, X-Client-Info, Apikey",
};

const SYSTEM_PROMPT = `You are MedFluent, an AI medical education assistant.

Your responsibility is to explain medical reports in plain language.

The user has provided an IMAGE of a medical report. Carefully read the image and extract the visible medical information before explaining it.

Important rules:
- Never diagnose diseases.
- Never recommend treatments.
- Never claim certainty.
- Never replace a healthcare professional.
- Always encourage users to discuss results with their doctor.
- Do not invent values that are not visible in the image.
- If part of the report is unclear or unreadable, explicitly say so.
- Preserve numerical values, units, test names, and reference ranges accurately.
- Distinguish between the patient's result and the laboratory's reference range.
- Do not assume a value is abnormal unless the report or reliable medical context supports that interpretation.

Always respond using this structure, with each section as a markdown heading:

# Summary

A brief explanation of what the report appears to describe.

# Plain Language Explanation

Explain the visible results in simple language that a non-medical person can understand.

# Medical Terms

List difficult medical terms found in the report and explain each one in plain language. Use a bulleted list.

# Questions To Ask Your Doctor

Generate useful questions the user should consider asking their doctor based on the report. Use a bulleted list.

# Learn More

For important medical terms, include links to trusted public health resources when available.

Only use these organizations and real resource pages:
- MedlinePlus
- World Health Organization
- American Heart Association
- American Diabetes Association
- National Kidney Foundation

Never fabricate links.

# Disclaimer

End with this exact text:

"This explanation is generated by AI for educational purposes only. It is not a diagnosis or medical advice. Please consult a qualified healthcare professional."`;

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    const authHeader = req.headers.get("Authorization");

    if (!authHeader) {
      return new Response(
        JSON.stringify({
          error: "Missing authorization header",
        }),
        {
          status: 401,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    const body = await req.json();

    const {
      image,
      language,
      reportId,
    } = body;

    if (!image || typeof image !== "string") {
      return new Response(
        JSON.stringify({
          error: "image is required",
        }),
        {
          status: 400,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    /*
     * Accept data URLs such as:
     * data:image/jpeg;base64,...
     *
     * We intentionally do NOT upload the image to Supabase Storage.
     */

    if (!image.startsWith("data:image/")) {
      return new Response(
        JSON.stringify({
          error: "Invalid image format. Please provide an image.",
        }),
        {
          status: 400,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    // Prevent unnecessarily huge requests.
    // The frontend should compress images before sending them.
    if (image.length > 15_000_000) {
      return new Response(
        JSON.stringify({
          error:
            "Image is too large. Please use a clear, smaller image of the report.",
        }),
        {
          status: 413,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    const aiApiKey = Deno.env.get("AI_API_KEY");

    if (!aiApiKey) {
      return new Response(
        JSON.stringify({
          error:
            "AI provider is not configured. Set AI_API_KEY in Supabase secrets.",
        }),
        {
          status: 500,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    const baseUrl =
      Deno.env.get("AI_BASE_URL") ||
      "https://openrouter.ai/api/v1";

    /*
     * Keep the image model configurable.
     *
     * We can change this through a Supabase secret without
     * changing the application code.
     */
    const model =
      Deno.env.get("AI_IMAGE_MODEL") ||
      "google/gemini-2.0-flash-001";

    const languageInstruction =
      language &&
      language.toLowerCase() !== "english"
        ? `Respond in ${language}, except keep the section headings in English.`
        : "Respond in English.";

    const userText = `Analyze this medical report image.

${languageInstruction}

Carefully read the report before explaining it.

If any text, number, unit, or reference range cannot be read confidently, say that it is unclear instead of guessing.`;

    const aiResponse = await fetch(
      `${baseUrl}/chat/completions`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${aiApiKey}`,
        },
        body: JSON.stringify({
          model,
          messages: [
            {
              role: "system",
              content: SYSTEM_PROMPT,
            },
            {
              role: "user",
              content: [
                {
                  type: "text",
                  text: userText,
                },
                {
                  type: "image_url",
                  image_url: {
                    url: image,
                  },
                },
              ],
            },
          ],
          temperature: 0.2,
        }),
      }
    );

    if (!aiResponse.ok) {
      const errText = await aiResponse.text();

      console.error(
        "OpenRouter error:",
        aiResponse.status,
        errText
      );

      return new Response(
  JSON.stringify({
    error: `AI provider error: ${aiResponse.status}`,
    detail: errText,
  }),
        {
          status: 502,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    const aiData = await aiResponse.json();

    const content =
      aiData?.choices?.[0]?.message?.content;

    if (!content || typeof content !== "string") {
      return new Response(
        JSON.stringify({
          error:
            "AI provider returned an empty or unexpected response.",
        }),
        {
          status: 502,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    /*
     * Save ONLY the AI-generated text.
     *
     * The image itself is never saved to Supabase Storage.
     */

    if (reportId) {
      const supabase = createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
        {
          auth: {
            persistSession: false,
          },
        }
      );

      const userJwt = authHeader.replace(
        "Bearer ",
        ""
      );

      const userClient = createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_ANON_KEY")!,
        {
          global: {
            headers: {
              Authorization: `Bearer ${userJwt}`,
            },
          },
          auth: {
            persistSession: false,
          },
        }
      );

      const { data: own } = await userClient
        .from("reports")
        .select("id")
        .eq("id", reportId)
        .maybeSingle();

      if (own) {
        await supabase
          .from("reports")
          .update({
            ai_response: content,
          })
          .eq("id", reportId);
      }
    }

    return new Response(
      JSON.stringify({
        analysis: content,
      }),
      {
        status: 200,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  } catch (err) {
    console.error("analyze-image error:", err);

    return new Response(
      JSON.stringify({
        error:
          err instanceof Error
            ? err.message
            : "Unexpected error",
      }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  }
});