export interface Profile {
  id: string;
  full_name: string | null;
  age: number | null;
  preferred_language: string;
  created_at: string;
}

export interface Report {
  id: string;
  user_id: string;
  original_text: string;
  ai_response: string | null;
  created_at: string;
}

export interface AnalysisSection {
  heading: string;
  body: string;
  items?: string[];
}

export const SUPPORTED_LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Portuguese',
  'Arabic',
  'Hindi',
  'Mandarin',
  'Russian',
  'Japanese',
] as const;

export const DISCLAIMER_TEXT =
  'This explanation is generated by AI for educational purposes only. It is not a diagnosis or medical advice. Please consult a qualified healthcare professional.';
