import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

const SYSTEM_PROMPT = `You are MedFluent, an AI medical education assistant.

Your responsibility is to explain medical reports in plain language.
Never diagnose diseases.
Never recommend treatments.
Never claim certainty.
Never replace a healthcare professional.
Always encourage users to discuss results with their doctor.

Always respond using this structure, with each section as a markdown heading:

# Summary
A brief explanation of what the report appears to describe.

# Plain Language Explanation
Explain everything in simple English that a non-medical person can understand.

# Medical Terms
List difficult medical terms found in the report and explain each one in plain language. Use a bulleted list.

# Questions To Ask Your Doctor
Generate useful questions the user should consider asking their doctor, based on the report. Use a bulleted list.

# Learn More
For important medical terms, include links to trusted public health resources when available. Only use these official organizations and their real, existing resource pages — never fabricate links:
- MedlinePlus (https://medlineplus.gov)
- World Health Organization (https://www.who.int)
- American Heart Association (https://www.heart.org)
- American Diabetes Association (https://diabetes.org)
- National Kidney Foundation (https://www.kidney.org)
If no trusted link is clearly relevant, say so rather than inventing one.

# Disclaimer
End with this exact text:
"This explanation is generated by AI for educational purposes only. It is not a diagnosis or medical advice. Please consult a qualified healthcare professional."`;

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Missing authorization header" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body = await req.json();
    const { reportText, language, reportId } = body;
    if (!reportText || typeof reportText !== "string") {
      return new Response(JSON.stringify({ error: "reportText is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const aiApiKey = Deno.env.get("AI_API_KEY") || Deno.env.get("VITE_AI_API_KEY");
    if (!aiApiKey) {
      return new Response(JSON.stringify({ error: "AI provider is not configured. Set AI_API_KEY in Supabase secrets." }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Build the user prompt. Optionally instruct the model to respond in a preferred language.
    const languageInstruction =
      language && language.toLowerCase() !== "english"
        ? `Respond in ${language}, except keep the section headings in English.`
        : "";
    const userPrompt = `Explain the following medical report.\n\n${languageInstruction}\n\nReport:\n"""${reportText.slice(0, 12000)}"""`;

    // Call the OpenAI-compatible Chat Completions endpoint.
    // Any OpenAI-compatible provider works by changing the base URL via AI_BASE_URL.
    const baseUrl = Deno.env.get("AI_BASE_URL") || "https://api.openai.com/v1";
    const model = Deno.env.get("AI_MODEL") || "gpt-4o-mini";

    const aiResponse = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${aiApiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3,
      }),
    });

    if (!aiResponse.ok) {
      const errText = await aiResponse.text();
      return new Response(JSON.stringify({ error: `AI provider error: ${aiResponse.status}`, detail: errText }), {
        status: 502,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const aiData = await aiResponse.json();
    const content = aiData?.choices?.[0]?.message?.content;
    if (!content) {
      return new Response(JSON.stringify({ error: "AI provider returned an empty response." }), {
        status: 502,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Persist the AI response back onto the report row, if a reportId was supplied.
    if (reportId) {
      const supabase = createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
        { auth: { persistSession: false } }
      );
      // Verify the report belongs to the caller before writing.
      const userJwt = authHeader.replace("Bearer ", "");
      const userClient = createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_ANON_KEY")!,
        { global: { headers: { Authorization: `Bearer ${userJwt}` } }, auth: { persistSession: false } }
      );
      const { data: own } = await userClient.from("reports").select("id").eq("id", reportId).maybeSingle();
      if (own) {
        await supabase.from("reports").update({ ai_response: content }).eq("id", reportId);
      }
    }

    return new Response(JSON.stringify({ analysis: content }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message || "Unexpected error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
